author: Dream
author_url: https://dream-swp.com
github_url: https://github.com/swp-song/DSBase
root_url: https://github.com/swp-song/DSBase
module: DSBase
output: Documentation
# theme: fullwidth
# theme: jony
theme: apple
# SMP
# text: ["--swift-build-tool", "spm"]
xcodebuild_arguments: ["-project", "DSBase.xcodeproj", "-scheme", "DSBase"]
#  jazzy